import { ClerkProvider } from '@clerk/nextjs'
import { frFR } from "@clerk/localizations";
import ModalsProvider from "../components/providers/modals-provider"


import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DevHunt 3.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={frFR}>
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ModalsProvider/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
